### ISSUE TITLE
problems with installing

### ISSUE THREAD

**Issue by benschofield** [mrkrasser/node-red-contrib-bmp085#6]
gyp WARN EACCES user "root" does not have permission to access the dev dir "/root/.node-gyp/0.12.6"
gyp WARN EACCES attempting to reinstall using temporary dev dir "/home/node_modules/node-red-contrib-bmp085/node_modules/bmp085/node_modules/i2c/.node-gyp"

npm ERR! i2c@0.1.8 install: `node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the i2c@0.1.8 install script 'node-gyp rebuild'.
npm ERR! This is most likely a problem with the i2c package,
npm ERR! not with npm itself.
npm ERR! Tell the author that this fails on your system:
npm ERR!     node-gyp rebuild
npm ERR! You can get their info via:
npm ERR!     npm owner ls i2c
npm ERR! There is likely additional logging output above.

npm ERR! Please include the following file with any support request:
npm ERR!     /home/pi/npm-debug.log

**Comment by mrkrasser** [comment]
Please follow this thread https://github.com/nodejs/node-gyp/issues/454
It solved by adding --unsafe-perm
