### ISSUE TITLE
Pressure output - too many decimal places

### ISSUE THREAD

**Issue by jamms** [mrkrasser/node-red-contrib-bmp085#8]
Hi Sergey,
I can see that around version 0.1.6 that the original pressure calculations were changed when sea level was added. The problem I have is that now, with the latest version the debug output i get in Node Red is showing the pressure to 13 or so decimal places, (e.g.752.1725854712103mmHg) so this does not match what is shown in the screengrabs.

I understand how the original pressure calculations worked, but not the new ones (I am fairly new to this). Could you show me how to fix the latest code to output the pressure to no decimal places again?

Jamms

**Comment by jamms** [comment]
Sergey,

Thanks, I see what you did there!

James

**Comment by mrkrasser** [comment]
James, not at all.
Good luck!
